FROM node:20-alpine
WORKDIR /app
COPY package.json ./
COPY apps/frontend/package.json ./apps/frontend/
RUN npm install
COPY apps/frontend ./apps/frontend
ENV NEXT_PUBLIC_API_URL=http://localhost:4000/api
RUN npm run build --workspace=apps/frontend
EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=apps/frontend"]
